// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtS0b0oD6qe8cNS-wrrhUfjy5Xd6gQiaM',
    appId: '1:363217250002:web:242b31586ceda85cee2f0b',
    messagingSenderId: '363217250002',
    projectId: 'martekunap',
    authDomain: 'martekunap.firebaseapp.com',
    storageBucket: 'martekunap.firebasestorage.app',
    measurementId: 'G-EMCSCHEEW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRgK26rFxqZdBJVe2UVF_B1uht31823k',
    appId: '1:363217250002:android:f53a1e7a5fb0c1c3ee2f0b',
    messagingSenderId: '363217250002',
    projectId: 'martekunap',
    storageBucket: 'martekunap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_W3UZajA0q6WO_rktCr3iokR0Ev0Dv4',
    appId: '1:363217250002:ios:c815294ce60fd6c1ee2f0b',
    messagingSenderId: '363217250002',
    projectId: 'martekunap',
    storageBucket: 'martekunap.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_W3UZajA0q6WO_rktCr3iokR0Ev0Dv4',
    appId: '1:363217250002:ios:c815294ce60fd6c1ee2f0b',
    messagingSenderId: '363217250002',
    projectId: 'martekunap',
    storageBucket: 'martekunap.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtS0b0oD6qe8cNS-wrrhUfjy5Xd6gQiaM',
    appId: '1:363217250002:web:42a27aa0c80d2005ee2f0b',
    messagingSenderId: '363217250002',
    projectId: 'martekunap',
    authDomain: 'martekunap.firebaseapp.com',
    storageBucket: 'martekunap.firebasestorage.app',
    measurementId: 'G-PMZBLSM41X',
  );
}
